// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktvdtpzutpwyzwdbyfqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dmR0cHp1dHB3eXp3ZGJ5ZnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTI3MzcsImV4cCI6MjA1OTk4ODczN30.XBstSt8AR6i_LlI5QPTb5wrOPCVv8uiPITc6YB_XY-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);